# run_anlaysis.R file

# Read relevant files from the downloaded UCI HAR Dataset appropriately 

setwd("C:/Shankar_PC/CopiedFromFreeAgent/Coursera/Getting and Cleaning Data/PROJ1/UCI HAR Dataset")


features<-read.table("features.txt")
activity_labels<-read.table("activity_lables.txt")


# Manipulation of " Test " data

#Parsing the "test" folder. The files of interest are : 
#X_test.txt,y_test.txt and subject_test.txt.


setwd("C:/Shankar_PC/CopiedFromFreeAgent/Coursera/Getting and Cleaning Data/PROJ1/UCI HAR Dataset/test")

# Read and take backups.

X_test<-read.table("X_test.txt")
X_test1<-X_test  

subject_test<-read.table("subject_test.txt")
subject_test1<-subject_test

y_test<-read.table("y_test.txt")
y_test1<-y_test

library(dplyr) # has many good summarization and grouping features.

# Converting into a table/DF to facilitate easy manipulation of data.
X_test<-tbl_df(X_test)

#Assigning the 561 variable names to the column names of X_test
colnames(X_test)<-features[,2]

#Getting the mean() and std() varaible names
meannames<-grep("mean()", features$V2, value=TRUE, fixed=TRUE)
stdnames<-grep("std()", features$V2, value=TRUE, fixed=TRUE)

#Subsetting X_test with variable names for mean and std.dev only.
X_test<-X_test[c(meannames,stdnames)]

#Combine the subject and activity to X_test->Prepend it to X_test
X_test_Act_Sub<-cbind(subject_test,y_test,X_test)

#Label the subject and activity names appropriately
colnames(X_train_Act_Sub)[1:2]<-c("Subject","Activity")

#verify X_test_Act_Sub has all the included columns.
names(X_test_Act_Sub)

#Assign activity names to all entries of "Activity" variable appropriately 

i<-0
for (i in 1:6) { 
        X_test_Act_Sub$Activity[X_test_Act_Sub$Activity == i]<-as.character(activity_labels$V2[i])
}


#=================================

# Manipulation of " Train " data

#Parsing the "train" folder. The files of interest are : 
# X_train.txt,y_train.txt and subject_train.txt.


setwd("C:/Shankar_PC/CopiedFromFreeAgent/Coursera/Getting and Cleaning Data/PROJ1/UCI HAR Dataset/test")

# Read and take backups.

X_train<-read.table("X_train.txt")
X_train1<-X_train 

subject_train<-read.table("subject.train.txt")
subject_train1<-subject_train

y_train<-read.table("y_train.txt")
y_train1<-y_train

library(dplyr) # has many good summarization and grouping features.

# Converting into a table/DF to facilitate easy manipulation of data.
X_train<-tbl_df(X_train)

#Assigning the 561 variable names to the column names of X_train
colnames(X_train)<-features[,2]

#Getting the mean() and std() varaible names
meannames<-grep("mean()", features$V2, value=TRUE, fixed=TRUE)
stdnames<-grep("std()", features$V2, value=TRUE, fixed=TRUE)

#Subsetting X_train with variable names for mean and std.dev only.
X_train<-X_train[c(meannames,stdnames)]

#Combine the subject and activity to X_test-Prepending it to X_train
X_train_Act_Sub<-cbind(subject_train,y_train,X_train)

#Label the subject and acitvity names appropriately
colnames(X_train_Act_Sub)[1:2]<-c("Subject","Activity")

#verify X_train_Act_Sub has all the included columns.
names(X_test_Act_Sub)

#Assign activity names to all entries of "Activity" variable appropriately 

i<-0
for (i in 1:6) { 
        X_train_Act_Sub$Activity[X_train_Act_Sub$Activity == i]<-as.character(activity_labels$V2[i])
}


#==========

# Combine train and test datas sets as below:
X_train_test_Act_Sub<-rbind(X_train_Act_Sub,X_test_Act_Sub)

#Rename the column names into descriptive variable names --STEP 4 of the project.
names(X_train_test_Act_Sub) <-gsub('\\(.*\\)', '', names(X_train_test_Act_Sub)) # remove "()"
names(X_train_test_Act_Sub) <--gsub('\\-', '_', names(X_train_test_Act_Sub)) # Replace "-" with "_"

# Change "Subject" and "Activity" to fcator variables to facilitate grouping.
X_train_test_Act_Sub$Subject<-as.factor(X_train_test_Act_Sub$Subject)
X_train_test_Act_Sub$Activity<-as.factor(X_train_test_Act_Sub$Activity)

# Group By Subject and Activity
m<-group_by(X_train_test_Act_Sub,Subject,Activity)


# function to generate variable assignments like "tBodyAcc_mean_X=mean(tBodyAcc_mean_X)" 
# for each of the 66 variables to be used later in summarize function.

Avg_Summary <-function(){
i<-0
for (i in 3:68){
        
        message ( colnames(m[i]),"=mean(",colnames(m[i]),"),")
        
        }
}

# Caculute average of each of the mean and std.dev variable grouped by Subject and Activity. 
# The variable assignments have been generated by the previous step and its output pasted here. 
Avg_Summary_by_Sub_Act<-summarize(m,
                                  tBodyAcc_mean_X=mean(tBodyAcc_mean_X),
                                  tBodyAcc_mean_Y=mean(tBodyAcc_mean_Y),
                                  tBodyAcc_mean_Z=mean(tBodyAcc_mean_Z),
                                  tGravityAcc_mean_X=mean(tGravityAcc_mean_X),
                                  tGravityAcc_mean_Y=mean(tGravityAcc_mean_Y),
                                  tGravityAcc_mean_Z=mean(tGravityAcc_mean_Z),
                                  tBodyAccJerk_mean_X=mean(tBodyAccJerk_mean_X),
                                  tBodyAccJerk_mean_Y=mean(tBodyAccJerk_mean_Y),
                                  tBodyAccJerk_mean_Z=mean(tBodyAccJerk_mean_Z),
                                  tBodyGyro_mean_X=mean(tBodyGyro_mean_X),
                                  tBodyGyro_mean_Y=mean(tBodyGyro_mean_Y),
                                  tBodyGyro_mean_Z=mean(tBodyGyro_mean_Z),
                                  tBodyGyroJerk_mean_X=mean(tBodyGyroJerk_mean_X),
                                  tBodyGyroJerk_mean_Y=mean(tBodyGyroJerk_mean_Y),
                                  tBodyGyroJerk_mean_Z=mean(tBodyGyroJerk_mean_Z),
                                  tBodyAccMag_mean=mean(tBodyAccMag_mean),
                                  tGravityAccMag_mean=mean(tGravityAccMag_mean),
                                  tBodyAccJerkMag_mean=mean(tBodyAccJerkMag_mean),
                                  tBodyGyroMag_mean=mean(tBodyGyroMag_mean),
                                  tBodyGyroJerkMag_mean=mean(tBodyGyroJerkMag_mean),
                                  fBodyAcc_mean_X=mean(fBodyAcc_mean_X),
                                  fBodyAcc_mean_Y=mean(fBodyAcc_mean_Y),
                                  fBodyAcc_mean_Z=mean(fBodyAcc_mean_Z),
                                  fBodyAccJerk_mean_X=mean(fBodyAccJerk_mean_X),
                                  fBodyAccJerk_mean_Y=mean(fBodyAccJerk_mean_Y),
                                  fBodyAccJerk_mean_Z=mean(fBodyAccJerk_mean_Z),
                                  fBodyGyro_mean_X=mean(fBodyGyro_mean_X),
                                  fBodyGyro_mean_Y=mean(fBodyGyro_mean_Y),
                                  fBodyGyro_mean_Z=mean(fBodyGyro_mean_Z),
                                  fBodyAccMag_mean=mean(fBodyAccMag_mean),
                                  fBodyBodyAccJerkMag_mean=mean(fBodyBodyAccJerkMag_mean),
                                  fBodyBodyGyroMag_mean=mean(fBodyBodyGyroMag_mean),
                                  fBodyBodyGyroJerkMag_mean=mean(fBodyBodyGyroJerkMag_mean),
                                  tBodyAcc_std_X=mean(tBodyAcc_std_X),
                                  tBodyAcc_std_Y=mean(tBodyAcc_std_Y),
                                  tBodyAcc_std_Z=mean(tBodyAcc_std_Z),
                                  tGravityAcc_std_X=mean(tGravityAcc_std_X),
                                  tGravityAcc_std_Y=mean(tGravityAcc_std_Y),
                                  tGravityAcc_std_Z=mean(tGravityAcc_std_Z),
                                  tBodyAccJerk_std_X=mean(tBodyAccJerk_std_X),
                                  tBodyAccJerk_std_Y=mean(tBodyAccJerk_std_Y),
                                  tBodyAccJerk_std_Z=mean(tBodyAccJerk_std_Z),
                                  tBodyGyro_std_X=mean(tBodyGyro_std_X),
                                  tBodyGyro_std_Y=mean(tBodyGyro_std_Y),
                                  tBodyGyro_std_Z=mean(tBodyGyro_std_Z),
                                  tBodyGyroJerk_std_X=mean(tBodyGyroJerk_std_X),
                                  tBodyGyroJerk_std_Y=mean(tBodyGyroJerk_std_Y),
                                  tBodyGyroJerk_std_Z=mean(tBodyGyroJerk_std_Z),
                                  tBodyAccMag_std=mean(tBodyAccMag_std),
                                  tGravityAccMag_std=mean(tGravityAccMag_std),
                                  tBodyAccJerkMag_std=mean(tBodyAccJerkMag_std),
                                  tBodyGyroMag_std=mean(tBodyGyroMag_std),
                                  tBodyGyroJerkMag_std=mean(tBodyGyroJerkMag_std),
                                  fBodyAcc_std_X=mean(fBodyAcc_std_X),
                                  fBodyAcc_std_Y=mean(fBodyAcc_std_Y),
                                  fBodyAcc_std_Z=mean(fBodyAcc_std_Z),
                                  fBodyAccJerk_std_X=mean(fBodyAccJerk_std_X),
                                  fBodyAccJerk_std_Y=mean(fBodyAccJerk_std_Y),
                                  fBodyAccJerk_std_Z=mean(fBodyAccJerk_std_Z),
                                  fBodyGyro_std_X=mean(fBodyGyro_std_X),
                                  fBodyGyro_std_Y=mean(fBodyGyro_std_Y),
                                  fBodyGyro_std_Z=mean(fBodyGyro_std_Z),
                                  fBodyAccMag_std=mean(fBodyAccMag_std),
                                  fBodyBodyAccJerkMag_std=mean(fBodyBodyAccJerkMag_std),
                                  fBodyBodyGyroMag_std=mean(fBodyBodyGyroMag_std),
                                  fBodyBodyGyroJerkMag_std=mean(fBodyBodyGyroJerkMag_std)
                                  )


library(tidyr)

# Step 5 final output.
# Below is the tidy data set- Has 4 columns - Subject,Activity, Mean_Std_Variables, Average. 
# Satisfies all criteria for a tidy data set.
        
Tidy_Avg_Summary_Final<-gather(Avg_Summary_by_Sub_Act,Mean_Std_Variables, Average,tBodyAcc_mean_X:fBodyBodyGyroJerkMag_std)

#Creating the final output text file in the working directory.
setwd("C:/Shankar_PC/CopiedFromFreeAgent/Coursera/Getting and Cleaning Data/PROJ1/UCI HAR Dataset")
 
write.table(Tidy_Avg_Summary_Final, file="Final_Tidy_Avg_Summary.txt", row.names=FALSE)

# The tidy data set is "Final_Tidy_Avg_Summary.txt" in the working directory.                            
                            